07-05-2020 16:44:09 DEBUG tests.test_acceptance.acceptance_base_class (test_check_column_length) Certificate column lengths:
0 : 11,
1 : 2,
2 : 10,
3 : 5
07-05-2020 16:44:09 DEBUG tests.test_acceptance.acceptance_base_class (test_check_column_nullables) Certificate column nullables:
0 : False,
1 : False,
2 : False,
3 : False
07-05-2020 16:44:09 DEBUG tests.test_acceptance.acceptance_base_class (test_check_column_number) Certificate 4 column number
07-05-2020 16:44:09 ERROR tests.test_acceptance.acceptance_base_class (test_check_column_number) Wrong column number: 4
Traceback (most recent call last):
  File "C:\Users\buzzulini\Documents\GitHub\I2FVG_scripts\innovation_intelligence\tests\test_acceptance\acceptance_base_class.py", line 41, in test_check_column_number
    self.assertEqual(expected_column_number, cert_column_number)
  File "C:\Users\buzzulini\.conda\envs\envWorking\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\buzzulini\.conda\envs\envWorking\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: NotImplemented != 4
07-05-2020 16:44:09 DEBUG tests.test_acceptance.acceptance_base_class (test_check_column_types) Certificate column types: 
0 : object,
1 : int64,
2 : datetime64[ns],
3 : object
07-05-2020 16:44:09 ERROR tests.test_acceptance.acceptance_base_class (test_check_column_types) Wrong column types:
0 : object,
1 : int64,
2 : datetime64[ns],
3 : object
Traceback (most recent call last):
  File "C:\Users\buzzulini\Documents\GitHub\I2FVG_scripts\innovation_intelligence\tests\test_acceptance\acceptance_base_class.py", line 61, in test_check_column_types
    self.assertEqual(expected_column_types, cert_column_types)
  File "C:\Users\buzzulini\.conda\envs\envWorking\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\buzzulini\.conda\envs\envWorking\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: NotImplemented != [dtype('O'), dtype('int64'), dtype('<M8[ns]'), dtype('O')]
07-05-2020 16:44:09 DEBUG tests.test_acceptance.acceptance_base_class (test_check_file_extension) Certificate csv file extension
07-05-2020 16:44:09 ERROR tests.test_acceptance.acceptance_base_class (test_check_file_extension) Wrong file extension: csv
Traceback (most recent call last):
  File "C:\Users\buzzulini\Documents\GitHub\I2FVG_scripts\innovation_intelligence\tests\test_acceptance\acceptance_base_class.py", line 25, in test_check_file_extension
    self.assertEqual(expected_file_extension, cert_file_extension)
  File "C:\Users\buzzulini\.conda\envs\envWorking\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\buzzulini\.conda\envs\envWorking\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: NotImplemented != 'csv'
